`zshrc`: fix `nvm` config setting

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -80,16 +80,17 @@ fi
 # https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-gpg-key
 export GPG_TTY=$(tty)
 
-if is_command_available nvm; then
-    # Added automatically from install script:
-    # https://github.com/nvm-sh/nvm#installing-and-updating
-    export NVM_DIR="$HOME/.nvm"
-    # This loads nvm
-    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-    # This loads nvm bash_completion
-    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
-else
-    echo "~/.zshrc: nvm is not available, can't set settings."
+# Added automatically from install script:  https://github.com/nvm-sh/nvm#installing-and-updating
+# Note that these lines aren't inside the `if` block because (1) they fail
+# gracefully if nvm is not installed, and (2) they are needed for the `nvm` to
+# be available in the first place.
+export NVM_DIR="$HOME/.nvm"
+# This loads nvm
+[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+# This loads nvm bash_completion
+[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
+if ! is_command_available nvm; then
+    echo "~/.zshrc: nvm is not available."
 fi
 
 ################################################################################
